name: Build macOS and Windows Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app pyinstaller

    - name: Build macOS .app file
      run: |
        python setup.py py2app

    - name: Build Windows installer
      run: |
        pyinstaller --onefile MyAmpSwitcher.py
        mv dist/MyAmpSwitcher dist/MyAmpSwitcher.exe  # Rename the executable

    - name: Zip macOS .app file
      run: |
        cd dist
        zip -r MyAmpSwitcher_macOS.zip MyAmpSwitcher.app

    - name: Zip Windows installer
      run: |
        cd dist
        zip -r MyAmpSwitcher_Windows.zip MyAmpSwitcher.exe

    - name: Upload macOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyAmpSwitcher_macOS
        path: dist/MyAmpSwitcher_macOS.zip  

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyAmpSwitcher_Windows
        path: dist/MyAmpSwitcher_Windows.zip  

  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: MyAmpSwitcher_macOS

      - name: Remove old macOS artifacts
        run: |
          if [ -f dist/MyAmpSwitcher_macOS.zip ]; then
            ls -1 | grep '_macOS.zip$' | sort -r | tail -n +3 | xargs rm -rf
          fi

      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: MyAmpSwitcher_Windows

      - name: Remove old Windows artifacts
        run: |
          if [ -f dist/MyAmpSwitcher_Windows.zip ]; then
            ls -1 | grep '_Windows.zip$' | sort -r | tail -n +3 | xargs rm -rf
          fi
