name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.yml'
      - '**/*.plist'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements.txt

    - name: Run tests and collect coverage report
      run: |
        python -m pytest -v  --cov=my-amp-switcher --cov-report=xml

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
